eureka:
   client:
      registryFetchIntervalSeconds: 5
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
   instance:
      health-check-url-path: /actuator/health
      instanceId: ${info.app.name}:${info.app.version}[${random.value}]
      leaseRenewalIntervalInSeconds: 5
      preferIpAddress: true
info:
   app:
      name: '@project.artifactId@'
      version: '@project.version@'
management:
   endpoints:
      web:
         exposure:
            include: gateway
spring:
   cloud:
      gateway:
         discovery:
            locator:
               enabled: true
               lowerCaseServiceId: true