eureka:
   client:
      healthcheck:
         enabled: false
      serviceUrl:
         defaultZone: http://localhost:8761/eureka/
   instance:
      instanceId: ${info.app.name}:${info.app.version}[${random.value}]
info:
   app:
      name: '@project.artifactId@'
      version: '@project.version@'